--
-- PostgreSQL database dump
--

\restrict Cz26UzgNEPCPXWOC7Hbpm2u6xH4Gwlz3r8F5s2dUCfM8rvv8fII66866meU3TnN

-- Dumped from database version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)
-- Dumped by pg_dump version 14.23 (Ubuntu 14.23-0ubuntu0.22.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: ai_request_logs; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.ai_request_logs (
    id bigint NOT NULL,
    main_topic character varying(255) NOT NULL,
    sub_topic character varying(255) NOT NULL,
    specific_topic character varying(255) NOT NULL,
    level character varying(20) NOT NULL,
    num_questions integer NOT NULL,
    num_answers integer NOT NULL,
    language character varying(2) NOT NULL,
    generation_mode character varying(20) NOT NULL,
    ai_prompt text NOT NULL,
    ai_response jsonb NOT NULL,
    ai_provider character varying(50) NOT NULL,
    ai_model character varying(100) NOT NULL,
    status character varying(20) NOT NULL,
    error_message text NOT NULL,
    response_time double precision NOT NULL,
    tokens_used integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    test_id bigint,
    user_id bigint NOT NULL
);


ALTER TABLE public.ai_request_logs OWNER TO angotest_dj_user;

--
-- Name: ai_request_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.ai_request_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.ai_request_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: answers; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.answers (
    id bigint NOT NULL,
    answer_text text NOT NULL,
    is_correct boolean NOT NULL,
    question_id bigint NOT NULL
);


ALTER TABLE public.answers OWNER TO angotest_dj_user;

--
-- Name: answers_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.answers ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.answers_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO angotest_dj_user;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO angotest_dj_user;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO angotest_dj_user;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO angotest_dj_user;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO angotest_dj_user;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO angotest_dj_user;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO angotest_dj_user;

--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.password_reset_tokens (
    id bigint NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.password_reset_tokens OWNER TO angotest_dj_user;

--
-- Name: password_reset_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: questions; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.questions (
    id bigint NOT NULL,
    question_text text NOT NULL,
    test_id bigint NOT NULL
);


ALTER TABLE public.questions OWNER TO angotest_dj_user;

--
-- Name: questions_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.questions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.questions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: results; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.results (
    id bigint NOT NULL,
    correct_answers integer NOT NULL,
    wrong_answers integer NOT NULL,
    time_taken integer NOT NULL,
    status character varying(20) NOT NULL,
    answers jsonb NOT NULL,
    started_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    test_id bigint NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.results OWNER TO angotest_dj_user;

--
-- Name: results_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.results ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.results_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: system_configs; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.system_configs (
    id bigint NOT NULL,
    key character varying(255) NOT NULL,
    value text NOT NULL,
    description text NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.system_configs OWNER TO angotest_dj_user;

--
-- Name: system_configs_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.system_configs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.system_configs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: test_invitations; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.test_invitations (
    id bigint NOT NULL,
    message text NOT NULL,
    token character varying(64) NOT NULL,
    is_used boolean NOT NULL,
    is_guest boolean NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    guest_user_id bigint,
    invited_by_id bigint NOT NULL,
    test_id bigint NOT NULL
);


ALTER TABLE public.test_invitations OWNER TO angotest_dj_user;

--
-- Name: test_invitations_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.test_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.test_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: tests; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.tests (
    id bigint NOT NULL,
    title character varying(255) NOT NULL,
    description text NOT NULL,
    main_topic character varying(255) NOT NULL,
    sub_topic character varying(255) NOT NULL,
    specific_topic character varying(255) NOT NULL,
    level character varying(20) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    created_by_id bigint NOT NULL
);


ALTER TABLE public.tests OWNER TO angotest_dj_user;

--
-- Name: tests_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.tests ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.tests_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: topics; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.topics (
    id bigint NOT NULL,
    main_topic character varying(200) NOT NULL,
    sub_topic character varying(200) NOT NULL,
    specific_topic character varying(200) NOT NULL,
    is_predefined boolean NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.topics OWNER TO angotest_dj_user;

--
-- Name: topics_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.topics ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.topics_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user_quotas; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.user_quotas (
    id bigint NOT NULL,
    month_year character varying(7) NOT NULL,
    max_requests integer NOT NULL,
    used_requests integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


ALTER TABLE public.user_quotas OWNER TO angotest_dj_user;

--
-- Name: user_quotas_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.user_quotas ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_quotas_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(50) NOT NULL,
    email character varying(100) NOT NULL,
    first_name character varying(50) NOT NULL,
    last_name character varying(50) NOT NULL,
    phone character varying(20) NOT NULL,
    address text NOT NULL,
    country character varying(100) NOT NULL,
    birth_date date,
    role character varying(20) NOT NULL,
    registered_at timestamp with time zone NOT NULL,
    login_at timestamp with time zone NOT NULL,
    is_active boolean NOT NULL,
    is_staff boolean NOT NULL,
    deleted_at timestamp with time zone
);


ALTER TABLE public.users OWNER TO angotest_dj_user;

--
-- Name: users_groups; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.users_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.users_groups OWNER TO angotest_dj_user;

--
-- Name: users_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.users_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users_user_permissions; Type: TABLE; Schema: public; Owner: angotest_dj_user
--

CREATE TABLE public.users_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.users_user_permissions OWNER TO angotest_dj_user;

--
-- Name: users_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE public.users_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: ai_request_logs ai_request_logs_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.ai_request_logs
    ADD CONSTRAINT ai_request_logs_pkey PRIMARY KEY (id);


--
-- Name: answers answers_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: password_reset_tokens password_reset_tokens_token_key; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_token_key UNIQUE (token);


--
-- Name: questions questions_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_pkey PRIMARY KEY (id);


--
-- Name: results results_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_pkey PRIMARY KEY (id);


--
-- Name: system_configs system_configs_key_key; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.system_configs
    ADD CONSTRAINT system_configs_key_key UNIQUE (key);


--
-- Name: system_configs system_configs_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.system_configs
    ADD CONSTRAINT system_configs_pkey PRIMARY KEY (id);


--
-- Name: test_invitations test_invitations_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.test_invitations
    ADD CONSTRAINT test_invitations_pkey PRIMARY KEY (id);


--
-- Name: test_invitations test_invitations_token_key; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.test_invitations
    ADD CONSTRAINT test_invitations_token_key UNIQUE (token);


--
-- Name: tests tests_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_pkey PRIMARY KEY (id);


--
-- Name: topics topics_main_topic_sub_topic_specific_topic_98f73bd2_uniq; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_main_topic_sub_topic_specific_topic_98f73bd2_uniq UNIQUE (main_topic, sub_topic, specific_topic);


--
-- Name: topics topics_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.topics
    ADD CONSTRAINT topics_pkey PRIMARY KEY (id);


--
-- Name: user_quotas user_quotas_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.user_quotas
    ADD CONSTRAINT user_quotas_pkey PRIMARY KEY (id);


--
-- Name: user_quotas user_quotas_user_id_month_year_87c2da38_uniq; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.user_quotas
    ADD CONSTRAINT user_quotas_user_id_month_year_87c2da38_uniq UNIQUE (user_id, month_year);


--
-- Name: users users_email_key; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);


--
-- Name: users_groups users_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_pkey PRIMARY KEY (id);


--
-- Name: users_groups users_groups_user_id_group_id_fc7788e8_uniq; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_group_id_fc7788e8_uniq UNIQUE (user_id, group_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: users_user_permissions users_user_permissions_user_id_permission_id_3b86cbdf_uniq; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_permission_id_3b86cbdf_uniq UNIQUE (user_id, permission_id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: ai_request__generat_17d3bd_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX ai_request__generat_17d3bd_idx ON public.ai_request_logs USING btree (generation_mode);


--
-- Name: ai_request__status_1b31a9_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX ai_request__status_1b31a9_idx ON public.ai_request_logs USING btree (status);


--
-- Name: ai_request__user_id_290115_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX ai_request__user_id_290115_idx ON public.ai_request_logs USING btree (user_id, created_at);


--
-- Name: ai_request_logs_test_id_60473618; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX ai_request_logs_test_id_60473618 ON public.ai_request_logs USING btree (test_id);


--
-- Name: ai_request_logs_user_id_aa118677; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX ai_request_logs_user_id_aa118677 ON public.ai_request_logs USING btree (user_id);


--
-- Name: answers_question_id_1c8a95ab; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX answers_question_id_1c8a95ab ON public.answers USING btree (question_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: password_re_token_b9e973_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX password_re_token_b9e973_idx ON public.password_reset_tokens USING btree (token, used, expires_at);


--
-- Name: password_reset_tokens_expires_at_f7ae145c; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX password_reset_tokens_expires_at_f7ae145c ON public.password_reset_tokens USING btree (expires_at);


--
-- Name: password_reset_tokens_token_81ae1aaf_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX password_reset_tokens_token_81ae1aaf_like ON public.password_reset_tokens USING btree (token varchar_pattern_ops);


--
-- Name: password_reset_tokens_used_6ced8e1e; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX password_reset_tokens_used_6ced8e1e ON public.password_reset_tokens USING btree (used);


--
-- Name: password_reset_tokens_user_id_0aeaaad3; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX password_reset_tokens_user_id_0aeaaad3 ON public.password_reset_tokens USING btree (user_id);


--
-- Name: questions_test_id_980bebe9; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX questions_test_id_980bebe9 ON public.questions USING btree (test_id);


--
-- Name: results_test_id_389021cd; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX results_test_id_389021cd ON public.results USING btree (test_id);


--
-- Name: results_test_id_dc7235_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX results_test_id_dc7235_idx ON public.results USING btree (test_id, status);


--
-- Name: results_user_id_12193d_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX results_user_id_12193d_idx ON public.results USING btree (user_id, status);


--
-- Name: results_user_id_1a41824a; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX results_user_id_1a41824a ON public.results USING btree (user_id);


--
-- Name: results_user_id_757cad_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX results_user_id_757cad_idx ON public.results USING btree (user_id, test_id, status);


--
-- Name: system_conf_key_4990ef_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX system_conf_key_4990ef_idx ON public.system_configs USING btree (key);


--
-- Name: system_configs_key_11a9602c_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX system_configs_key_11a9602c_like ON public.system_configs USING btree (key varchar_pattern_ops);


--
-- Name: test_invita_expires_e6d21e_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invita_expires_e6d21e_idx ON public.test_invitations USING btree (expires_at);


--
-- Name: test_invita_guest_u_97df05_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invita_guest_u_97df05_idx ON public.test_invitations USING btree (guest_user_id, is_used);


--
-- Name: test_invita_invited_ca22cc_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invita_invited_ca22cc_idx ON public.test_invitations USING btree (invited_by_id, created_at);


--
-- Name: test_invita_test_id_69d67a_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invita_test_id_69d67a_idx ON public.test_invitations USING btree (test_id, is_used);


--
-- Name: test_invita_token_aeca6f_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invita_token_aeca6f_idx ON public.test_invitations USING btree (token);


--
-- Name: test_invitations_guest_user_id_3b596f7f; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invitations_guest_user_id_3b596f7f ON public.test_invitations USING btree (guest_user_id);


--
-- Name: test_invitations_invited_by_id_c6064ff7; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invitations_invited_by_id_c6064ff7 ON public.test_invitations USING btree (invited_by_id);


--
-- Name: test_invitations_is_guest_c2c555c3; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invitations_is_guest_c2c555c3 ON public.test_invitations USING btree (is_guest);


--
-- Name: test_invitations_is_used_28f2612b; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invitations_is_used_28f2612b ON public.test_invitations USING btree (is_used);


--
-- Name: test_invitations_test_id_8aa64f38; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invitations_test_id_8aa64f38 ON public.test_invitations USING btree (test_id);


--
-- Name: test_invitations_token_62e1b158_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX test_invitations_token_62e1b158_like ON public.test_invitations USING btree (token varchar_pattern_ops);


--
-- Name: tests_created_by_id_3fa35d1a; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX tests_created_by_id_3fa35d1a ON public.tests USING btree (created_by_id);


--
-- Name: tests_is_acti_ec1450_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX tests_is_acti_ec1450_idx ON public.tests USING btree (is_active);


--
-- Name: tests_level_67d00a_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX tests_level_67d00a_idx ON public.tests USING btree (level);


--
-- Name: tests_main_to_06297c_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX tests_main_to_06297c_idx ON public.tests USING btree (main_topic, sub_topic);


--
-- Name: topics_main_to_44c819_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_main_to_44c819_idx ON public.topics USING btree (main_topic, sub_topic);


--
-- Name: topics_main_to_7b95fc_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_main_to_7b95fc_idx ON public.topics USING btree (main_topic);


--
-- Name: topics_main_to_a49daa_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_main_to_a49daa_idx ON public.topics USING btree (main_topic, sub_topic, specific_topic);


--
-- Name: topics_main_topic_fda47aa5; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_main_topic_fda47aa5 ON public.topics USING btree (main_topic);


--
-- Name: topics_main_topic_fda47aa5_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_main_topic_fda47aa5_like ON public.topics USING btree (main_topic varchar_pattern_ops);


--
-- Name: topics_specific_topic_e5075fbd; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_specific_topic_e5075fbd ON public.topics USING btree (specific_topic);


--
-- Name: topics_specific_topic_e5075fbd_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_specific_topic_e5075fbd_like ON public.topics USING btree (specific_topic varchar_pattern_ops);


--
-- Name: topics_sub_topic_145560c8; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_sub_topic_145560c8 ON public.topics USING btree (sub_topic);


--
-- Name: topics_sub_topic_145560c8_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX topics_sub_topic_145560c8_like ON public.topics USING btree (sub_topic varchar_pattern_ops);


--
-- Name: user_quotas_max_req_98d6e0_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX user_quotas_max_req_98d6e0_idx ON public.user_quotas USING btree (max_requests);


--
-- Name: user_quotas_month_y_f82032_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX user_quotas_month_y_f82032_idx ON public.user_quotas USING btree (month_year);


--
-- Name: user_quotas_month_year_8d82b269; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX user_quotas_month_year_8d82b269 ON public.user_quotas USING btree (month_year);


--
-- Name: user_quotas_month_year_8d82b269_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX user_quotas_month_year_8d82b269_like ON public.user_quotas USING btree (month_year varchar_pattern_ops);


--
-- Name: user_quotas_used_re_d67581_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX user_quotas_used_re_d67581_idx ON public.user_quotas USING btree (used_requests);


--
-- Name: user_quotas_user_id_32716608; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX user_quotas_user_id_32716608 ON public.user_quotas USING btree (user_id);


--
-- Name: user_quotas_user_id_435993_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX user_quotas_user_id_435993_idx ON public.user_quotas USING btree (user_id, month_year);


--
-- Name: users_country_2c26a636; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_country_2c26a636 ON public.users USING btree (country);


--
-- Name: users_country_2c26a636_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_country_2c26a636_like ON public.users USING btree (country varchar_pattern_ops);


--
-- Name: users_deleted_at_eb2c3563; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_deleted_at_eb2c3563 ON public.users USING btree (deleted_at);


--
-- Name: users_email_0ea73cca_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_email_0ea73cca_like ON public.users USING btree (email varchar_pattern_ops);


--
-- Name: users_groups_group_id_2f3517aa; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_groups_group_id_2f3517aa ON public.users_groups USING btree (group_id);


--
-- Name: users_groups_user_id_f500bee5; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_groups_user_id_f500bee5 ON public.users_groups USING btree (user_id);


--
-- Name: users_is_active_1197087a; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_is_active_1197087a ON public.users USING btree (is_active);


--
-- Name: users_registe_85683b_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_registe_85683b_idx ON public.users USING btree (registered_at);


--
-- Name: users_registered_at_0c1cf063; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_registered_at_0c1cf063 ON public.users USING btree (registered_at);


--
-- Name: users_role_a8f2ba_idx; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_role_a8f2ba_idx ON public.users USING btree (role, is_active);


--
-- Name: users_role_f0571928; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_role_f0571928 ON public.users USING btree (role);


--
-- Name: users_role_f0571928_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_role_f0571928_like ON public.users USING btree (role varchar_pattern_ops);


--
-- Name: users_user_permissions_permission_id_6d08dcd2; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_user_permissions_permission_id_6d08dcd2 ON public.users_user_permissions USING btree (permission_id);


--
-- Name: users_user_permissions_user_id_92473840; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_user_permissions_user_id_92473840 ON public.users_user_permissions USING btree (user_id);


--
-- Name: users_username_e8658fc8_like; Type: INDEX; Schema: public; Owner: angotest_dj_user
--

CREATE INDEX users_username_e8658fc8_like ON public.users USING btree (username varchar_pattern_ops);


--
-- Name: ai_request_logs ai_request_logs_test_id_60473618_fk_tests_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.ai_request_logs
    ADD CONSTRAINT ai_request_logs_test_id_60473618_fk_tests_id FOREIGN KEY (test_id) REFERENCES public.tests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: ai_request_logs ai_request_logs_user_id_aa118677_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.ai_request_logs
    ADD CONSTRAINT ai_request_logs_user_id_aa118677_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: answers answers_question_id_1c8a95ab_fk_questions_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.answers
    ADD CONSTRAINT answers_question_id_1c8a95ab_fk_questions_id FOREIGN KEY (question_id) REFERENCES public.questions(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: password_reset_tokens password_reset_tokens_user_id_0aeaaad3_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_user_id_0aeaaad3_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: questions questions_test_id_980bebe9_fk_tests_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.questions
    ADD CONSTRAINT questions_test_id_980bebe9_fk_tests_id FOREIGN KEY (test_id) REFERENCES public.tests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: results results_test_id_389021cd_fk_tests_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_test_id_389021cd_fk_tests_id FOREIGN KEY (test_id) REFERENCES public.tests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: results results_user_id_1a41824a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.results
    ADD CONSTRAINT results_user_id_1a41824a_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: test_invitations test_invitations_guest_user_id_3b596f7f_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.test_invitations
    ADD CONSTRAINT test_invitations_guest_user_id_3b596f7f_fk_users_id FOREIGN KEY (guest_user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: test_invitations test_invitations_invited_by_id_c6064ff7_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.test_invitations
    ADD CONSTRAINT test_invitations_invited_by_id_c6064ff7_fk_users_id FOREIGN KEY (invited_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: test_invitations test_invitations_test_id_8aa64f38_fk_tests_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.test_invitations
    ADD CONSTRAINT test_invitations_test_id_8aa64f38_fk_tests_id FOREIGN KEY (test_id) REFERENCES public.tests(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: tests tests_created_by_id_3fa35d1a_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.tests
    ADD CONSTRAINT tests_created_by_id_3fa35d1a_fk_users_id FOREIGN KEY (created_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: user_quotas user_quotas_user_id_32716608_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.user_quotas
    ADD CONSTRAINT user_quotas_user_id_32716608_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_group_id_2f3517aa_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_group_id_2f3517aa_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_groups users_groups_user_id_f500bee5_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_groups
    ADD CONSTRAINT users_groups_user_id_f500bee5_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissio_permission_id_6d08dcd2_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissio_permission_id_6d08dcd2_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: users_user_permissions users_user_permissions_user_id_92473840_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: angotest_dj_user
--

ALTER TABLE ONLY public.users_user_permissions
    ADD CONSTRAINT users_user_permissions_user_id_92473840_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict Cz26UzgNEPCPXWOC7Hbpm2u6xH4Gwlz3r8F5s2dUCfM8rvv8fII66866meU3TnN

